### ISSUE TITLE
These directions don't work for IDE 3

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/rack-http-request-readme#5]
This section of directions don't work, explanation below: 

"Now we put all of your items out. The problem though is that this will list all of your items no matter what path you put in. Give it a try. Create your Rack file with the above code. Type localhost:9292/items, localhost:9292/cart, localhost:9292/flatiron/is/awesome. All of those URLs work since we're not filtering for path. In other words, no matter what the request is, we send the same response. Let's filter so that this only works for the /items path using the #path method of our Rack::Request object:"

--one of the issues is that this lesson doesn't have a blue OPEN IDE button, which it needs so a student can code along. THat would be a great addition because at this point, a student hasn't done rails, and we don't know how to rails-generate the files we need. 
Thanks for considering.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. You should now be able to use the `sandbox` to code along.

>Note: If you're using the sandbox, you won't be able to get to your website with localhost. Instead, you'll see a line that looks something like this - Starting server on 159.203.101.28:30001. To see the webpage, just go to 159.203.101.28:30001 in your web browser. Anywhere these instructions tell you to go to localhost, replace that with this IP address instead!

As always thank you for contributing!

**Comment by MiriamPeskowitz** [comment]
Hi Jason, 

Thanks! 

Miriam 


Miriam Peskowitz
Author, The Daring Book for Girls
and Code Like a Girl (coming in September 2018)
miriam5000@gmail.com


On Mar 15, 2018, at 2:28 PM, Jason Decker <notifications@github.com> wrote:

Hi there,

Thank you for bringing this to our attention. You should now be able to use the sandbox to code along.

Note: If you're using the sandbox, you won't be able to get to your website with localhost. Instead, you'll see a line that looks something like this - Starting server on 159.203.101.28:30001. To see the webpage, just go to 159.203.101.28:30001 in your web browser. Anywhere these instructions tell you to go to localhost, replace that with this IP address instead!

As always thank you for contributing!
