### ISSUE TITLE
You cannot inspect #path per the instructions if using the Learn IDE

### ISSUE THREAD

**Issue by schanrai** [learn-co-curriculum/rack-http-request-readme#6]
Unless you are on a local environment which  you are not encouraged to do at this stage of the course it is not possible to try this out - "Create your Rack file with the above code. Type localhost:9292/items, localhost:9292/cart, localhost:9292/flatiron/is/awesome. All of those URLs work since we're not filtering for path. In other words, no matter what the request is, we send the same response. Let's filter so that this only works for the /items path using the #path method of our Rack::Request object:"

**Comment by jenmyers** [comment]
Hello! We have clarified the wording of these instructions so that it's targeted better at those working on a local environment.
